# 启动本地服务配置
server:
  port: 3000
  origin: 'localhost'

# 数据库配置
db:
  type: 'mysql' # 数据库类型
  port: 3306 # 端口号
  timezone: '+08:00' # 服务器上配置的时区 - 东八时区

# jwt配置
jwt:
  expiresIn: '1d'

# 微信小程序配置
mp-wx:
  appid: 'wx4e02241c758c34c0'
  secret: 'd5328d606a31794bd166d3dbfd1b01fd'
