# 启动本地服务配置
server:
  port: 3000
  origin: 'localhost'

# 数据库配置
db:
  type: 'mysql' # 数据库类型
  port: 13306 # 端口号
  timezone: 'Z' # 服务器上配置的时区 - 东八时区

# jwt配置
jwt:
  expiresIn: '1d'

# 微信小程序配置
mp-wx:
  appid: 'wx4e02241c758c34c0'
  secret: 'd5328d606a31794bd166d3dbfd1b01fd'

# oss-七牛 配置
oss-qiniu:
  OSS_QINIU_AK: 'HQZPutNeXgQBgg1G3hhlR_eL-EB1CWyNwoaTYkjB'
  OSS_QINIU_SK: 'a0lGUVwkdSHuZ-29-Q6npTmTW78gi_hMuFtEU7I5'
  OSS_QINIU_BUCKET: 'rock-qiniu-pic'
  OSS_QINIU_DOMAIN: 'http(s)://rock-qiniu-pic.s3.cn-north-1.qiniucs.com'
