name: Deploy to Server

on:
  push:
    branches: ['main']
    paths-ignore: # 忽略一些不必要的文件
      - '.gitignore'
      - 'README.md'
      - '.vscode/**'
    pull_request:
      branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io # 声明镜像源
          username: ${{ github.actor }} # 当前github 用户名
          password: ${{ secrets.HUB_GITHUB_TOKEN }} # 需要去 https://github.com/settings/tokens 生成一个 名为 token，注意此token 需要读写 packages 等权限

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Show Dir
        run: ls

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run:
          | # 使用 上一步写的 Dockerfile 构建镜像并发布到私有仓库； 发布完成可以去 https://github.com/MrGaoGang?tab=packages 查看
          docker build . --file Dockerfile --tag ghcr.io/rockchang0556/nestjsbackend:latest
          docker push ghcr.io/rockchang0556/nestjs-backend:latest

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-backend:latest

      # - name: Copy Docker Compose file to server
      #   uses: appleboy/scp-action@v0.1.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_PRIVATE_KEY }}
      #     source: 'docker-compose.yml'
      #     target: '/home/${{ secrets.SERVER_USERNAME }}/nestjs-backend/'

      # - name: SSH to server and deploy
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_PRIVATE_KEY }}
      #     script: |
      #       cd /home/${{ secrets.SERVER_USERNAME }}/my-nestjs-app
      #       docker-compose down
      #       docker-compose up -d
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
          username: ${{ secrets.SERVER_USERNAME }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
          password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
          port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
          script: | # 重启更新镜像
            docker stop nestjs-backend
            docker rm nestjs-backend
            docker login -u ${{ github.actor }} -p ${{ secrets.HUB_GITHUB_TOKEN }} https://ghcr.io
            docker pull ghcr.io/${{ github.actor }}/nestjs-backend:latest
            docker run -dp 80:80  --restart=always --name nestjs-backend ghcr.io/${{ github.actor }}/nestjs-backend
