name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'dev']
    paths-ignore: # 忽略一些不必要的文件
      - '.gitignore'
      - 'README.md'
      - '.vscode/**'
      - 'document/**'
      - 'logs/**'
  pull_request:
    branches: ['main', 'dev']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ toLower(github.repository) }}

jobs:
  # 代码质量检查
  quality-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

  # 构建和部署
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [quality-check]
    # 如果 quality-check 被跳过，则不需要等待
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && (needs.quality-check.result == 'success' || needs.quality-check.result == 'skipped')
    outputs:
      image-tag: ${{ steps.vars.outputs.build_tag }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.HUB_GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Get short SHA and build tag
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_tag=${{ github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.build_tag }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy deployment files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'docker-compose-1panel.yml,nginx.conf,deploy-1panel.sh,setup-1panel.sh'
          target: '/home/${{ secrets.SERVER_USERNAME }}/nestjs-backend/'

      - name: Deploy to server with 1Panel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            # 进入部署目录
            cd /home/${{ secrets.SERVER_USERNAME }}/nestjs-backend/

            # 设置执行权限
            chmod +x deploy-1panel.sh

            # 登录到容器注册表
            echo "${{ secrets.HUB_GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            # 使用 1Panel 优化脚本部署
            ./deploy-1panel.sh production "${{ steps.vars.outputs.build_tag }}"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ 部署成功完成！"
          else
            echo "❌ 部署失败，请检查日志"
          fi
